import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import{ArrowUpRight,BookOpen,Briefcase,ChevronRight,Code2,Compass,ExternalLink,Globe2,Layers3,Mail,Menu,Play,Quote,Send,Sparkles,TrendingUp,X}from'lucide-react';import'./index.css';

type Project={title:string;kind:string;desc:string;url:string;tags:string[]};
const projects:Project[]=[{title:'JRH Portfolio',kind:'Personal digital space',desc:'A living interface for ideas, experiments, economics, technology and projects.',url:'https://github.com/LionerHakim/JRHs',tags:['React','Vite','Design']},{title:'KitaBisa.com',kind:'Web experiment',desc:'A front-end exploration inspired by modern product interfaces and digital services.',url:'https://github.com/LionerHakim/KITABISA.COM',tags:['Web','UI','Experiment']},{title:'Ultah',kind:'Creative web',desc:'A small interactive web experience built around storytelling and motion.',url:'https://github.com/LionerHakim/Ultah',tags:['Creative','Motion','Web']}];
function App(){const[dark,setDark]=useState(false);const[open,setOpen]=useState(false);const[active,setActive]=useState('Home');useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light'},[dark]);const nav=(id:string)=>{setActive(id);setOpen(false);document.getElementById(id.toLowerCase())?.scrollIntoView({behavior:'smooth'})};return <div className="app"><header className="nav"><button className="brand" onClick={()=>nav('Home')}><span>J</span> JRH</button><nav className={open?'open':''}>{['Home','About','Experience','Projects','Contact'].map(x=><button key={x} className={active===x?'selected':''} onClick={()=>nav(x)}>{x}</button>)}</nav><div className="nav-actions"><button className="theme" onClick={()=>setDark(!dark)} aria-label="Toggle theme"><i className={dark?'moon':'sun'}/></button><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header>
<main><section id="home" className="hero"><div className="hero-copy"><div className="eyebrow"><span className="live"/> DIGITAL SPACE · 2026</div><h1>Think different.<br/><em>Build what matters.</em></h1><p>Jefri Rahman Hakim — economic thinker, builder, trader, and curious human exploring the intersection of <strong>economics × technology × ideas.</strong></p><div className="hero-actions"><button className="primary" onClick={()=>nav('Projects')}>Explore work <ArrowUpRight size={17}/></button><button className="ghost" onClick={()=>nav('About')}>About JRH <ChevronRight size={16}/></button></div></div><div className="orb-card"><div className="orb"><span>JRH</span></div><div className="orb-meta"><span>NOW EXPLORING</span><strong>Ideas → Systems → Reality</strong></div></div></section>
<section id="about" className="section"><div className="section-head"><div><span className="kicker">01 / ABOUT</span><h2>A digital space,<br/><em>not just a portfolio.</em></h2></div><p>This site is a compact map of what I learn, build, test and question. Minimal on the surface; layered underneath.</p></div><div className="about-grid"><article className="glass large"><Sparkles/><span>CORE</span><h3>Curiosity<br/>as a system.</h3><p>Economics, markets, AI, blockchain, Web3 and human behavior — connected through one question: “why?”</p></article><article className="glass"><TrendingUp/><span>FOCUS</span><h3>Economics<br/>& markets.</h3><p>Development economics, financial literacy, investing and market behavior.</p></article><article className="glass"><Code2/><span>BUILD</span><h3>Digital<br/>experiments.</h3><p>Web products, AI workflows and interfaces that turn ideas into something usable.</p></article></div></section>
<section id="experience" className="section timeline"><div className="section-head"><div><span className="kicker">02 / EXPERIENCE</span><h2>The trail<br/><em>so far.</em></h2></div><p>Not a conventional résumé. A sequence of things that shaped the way I think and build.</p></div><div className="timeline-list"><div><b>2026</b><span/><article><small>UNIVERSITY · UII</small><h3>Development Economics</h3><p>Final-stage academic work with a focus on financial literacy, investment readiness and digital education.</p></article></div><div><b>2025</b><span/><article><small>PROJECTS · INDEPENDENT</small><h3>Building in public</h3><p>Experimenting with web products, AI, crypto, trading systems and personal digital infrastructure.</p></article></div><div><b>PAST</b><span/><article><small>FOUNDATIONS</small><h3>Organization & leadership</h3><p>OSIS, Paskibra and student communities shaped the early habit of organizing people and ideas.</p></article></div></div></section>
<section id="projects" className="section projects"><div className="section-head"><div><span className="kicker">03 / SELECTED WORK</span><h2>Small projects.<br/><em>Real experiments.</em></h2></div><p>Three snapshots. The point isn't volume — it's learning by shipping.</p></div><div className="project-row">{projects.map((p,i)=><article className="project" key={p.title}><div className={'project-art art'+i}><span>0{i+1}</span><Layers3/></div><div className="project-body"><div><small>{p.kind}</small><h3>{p.title}</h3></div><p>{p.desc}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><a href={p.url} target="_blank" rel="noreferrer">View project <ExternalLink size={14}/></a></div></article>)}</div></section>
<section className="quote"><Quote size={28}/><blockquote>“The best interface is the one that makes complexity feel inevitable.”</blockquote><span>JRH · NOTES</span></section>
<section id="contact" className="section contact"><div className="contact-card"><div><span className="kicker">04 / CONTACT</span><h2>Have an idea?<br/><em>Let's make it real.</em></h2><p>Open to interesting conversations, collaborations, research, digital products and ambitious experiments.</p></div><div className="contact-links"><a href="https://instagram.com/jefrirh_" target="_blank" rel="noreferrer"><Globe2/> Instagram <ArrowUpRight/></a><a href="https://github.com/LionerHakim/JRHs" target="_blank" rel="noreferrer"><Code2/> GitHub <ArrowUpRight/></a></div></div></section></main>
<footer><div><b>JRH</b><span>Berpikir, membangun, dan terus mengeksplorasi.</span></div><small>© 2026 JRH · Indonesia</small></footer></div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);